examples/Uber.Website/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Uber.Website.Helpers;

namespace Uber.Website.Controllers
{
    public class AuthController : Controller
    {
        public ActionResult Index()
        {
            var scopes = new List<string> { "profile", "history_lite", "request" };

            var uberClient = UberClientHelper.GetAuth();
            var response = uberClient.GetAuthorizeUrl(scopes, Guid.NewGuid().ToString());

            return View("Index", (object)response);
        }

        public async Task<ActionResult> Callback(string code)
        {
            var uberClient = UberClientHelper.GetAuth();
            var accessToken = await uberClient.GetAccessTokenAsync(code, "http://localhost:7090/auth/callback");

            if (accessToken == null || string.IsNullOrWhiteSpace(accessToken.Value))
            {
                return RedirectToAction("Index");
            }

            CookieHelper.SetAccessToken(accessToken);

            return View();
        }
    }
}

examples/Uber.Website/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Uber.Website.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

examples/Uber.Website/Controllers/PriceEstimateController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Uber.SDK;
using Uber.Website.Helpers;

namespace Uber.Website.Controllers
{
    public class PriceEstimateController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(float startlat, float startlng, float endlat, float endlng)
        {
            var uberClient = UberClientHelper.Get();
            var prices = await uberClient.GetPriceEstimateAsync(startlat, startlng, endlat, endlng);

            return View("Results", prices.Data);
        }
    }
}

examples/Uber.Website/Controllers/ProductController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Uber.SDK;
using Uber.Website.Helpers;

namespace Uber.Website.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(float startlat, float startlng)
        {
            var uberClient = UberClientHelper.Get();
            var products = await uberClient.GetProductsAsync(startlat, startlng);

            return View("Results", products.Data);
        }
    }
}

examples/Uber.Website/Controllers/RequestController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Uber.SDK;
using Uber.Website.Helpers;

namespace Uber.Website.Controllers
{
    public class RequestController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var auth = CookieHelper.GetAccessToken();
            if (auth == null)
            {
                return RedirectToAction("Index", "Auth");
            }

            var uberClient = UberClientHelper.Get(auth.Value);
            var userActivity = await uberClient.GetUserActivityAsync(0, 50);

            return View(userActivity.Data);
        }

        public async Task<ActionResult> Show(string requestId)
        {
            var auth = CookieHelper.GetAccessToken();
            if (auth == null)
            {
                return RedirectToAction("Index", "Auth");
            }

            var uberClient = UberClientHelper.Get(auth.Value);
            var request = await uberClient.GetRequestDetailsAsync(requestId);

            return View(request.Data);
        }

        public async Task<ActionResult> Create()
        {
            var auth = CookieHelper.GetAccessToken();
            if (auth == null)
            {
                return RedirectToAction("Index", "Auth");
            }

            var uberClient = UberClientHelper.Get(auth.Value);
            var products = await uberClient.GetProductsAsync(-37.8602828f, 145.079616f);
            ViewBag.ProductId = products.Data.Products.First().ProductId;

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(string productId, float startlat, float startlng, float endlat, float endlng)
        {
            var auth = CookieHelper.GetAccessToken();
            if (auth == null)
            {
                return RedirectToAction("Index", "Auth");
            }

            var uberClient = UberClientHelper.Get(auth.Value);
            var request = await uberClient.RequestAsync(productId, startlat, startlng, endlat, endlng);

            return RedirectToAction("Show", new { requestId = request.Data.RequestId });
        }

        public async Task<ActionResult> Cancel(string requestId)
        {
            var auth = CookieHelper.GetAccessToken();
            if (auth == null)
            {
                return RedirectToAction("Index", "Auth");
            }

            var uberClient = UberClientHelper.Get(auth.Value);
            var request = await uberClient.CancelRequestAsync(requestId);

            return View(request.Data);
        }

        public async Task<ActionResult> Map(string requestId)
        {
            var auth = CookieHelper.GetAccessToken();
            if (auth == null)
            {
                return RedirectToAction("Index", "Auth");
            }

            var uberClient = UberClientHelper.Get(auth.Value);
            var request = await uberClient.GetRequestMapAsync(requestId);

            return View(request.Data);
        }

        public async Task<ActionResult> UpdateStatus(string requestId, string status)
        {
            var auth = CookieHelper.GetAccessToken();
            if (auth == null)
            {
                return RedirectToAction("Index", "Auth");
            }

            var uberClient = UberClientHelper.Get(auth.Value);
            await uberClient.UpdateRequestStatus(requestId, status);

            return RedirectToAction("Show", new { requestId = requestId });
        }
    }
}

examples/Uber.Website/Controllers/TimeEstimateController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Uber.SDK;
using Uber.Website.Helpers;

namespace Uber.Website.Controllers
{
    public class TimeEstimateController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(float startlat, float startlng)
        {
            var uberClient = UberClientHelper.Get();
            var times = await uberClient.GetTimeEstimateAsync(startlat, startlng);

            return View("Results", times.Data);
        }
    }
}

examples/Uber.Website/Controllers/UserController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Uber.Website.Helpers;

namespace Uber.Website.Controllers
{
    public class UserController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var auth = CookieHelper.GetAccessToken();
            if (auth == null)
            {
                return RedirectToAction("Index", "Auth");
            }

            var uberClient = UberClientHelper.Get(auth.Value);
            var userProfile = await uberClient.GetUserProfileAsync();

            return View(userProfile.Data);
        }
    }
}

examples/Uber.Website/Views/Home/Index.cshtml
@model string
@{
    ViewBag.Title = "Home";
}
<p>Get a @Html.ActionLink("price estimate.", "Index", "PriceEstimate")</p>
<p>Get a @Html.ActionLink("time estimate.", "Index", "TimeEstimate")</p>
<p>View some @Html.ActionLink("products.", "Index", "Product")</p>
<p>View your @Html.ActionLink("user profile.", "Index", "User")</p>
<p>View your @Html.ActionLink("requests.", "Index", "Request")</p>
<p>Make a @Html.ActionLink("request.", "Create", "Request")</p>
<p>Haven't authenticated yet?</p>
<p>@Html.ActionLink("Authenticate", "Index", "Auth")</p>

examples/Uber.Website/Views/PriceEstimate/Index.cshtml
@{
    ViewBag.Title = "Price estimates";
}
<h2>@ViewBag.Title</h2>
@using (Html.BeginForm())
{
    <div>
        <label for="startlat">Start latitude</label>
        <input type="text" name="startlat" value="-37.8602828" />
    </div>
    <div>
        <label for="startlng">Start longitude</label>
        <input type="text" name="startlng" value="145.079616" />
    </div>
    <div>
        <label for="endlat">End latitude</label>
        <input type="text" name="endlat" value="-38.3436789" />
    </div>
    <div>
        <label for="endlng">End longitude</label>
        <input type="text" name="endlng" value="144.7430275" />
    </div>
    <div>
        <input type="submit" value="Go" />
    </div>
}

examples/Uber.Website/Views/PriceEstimate/Results.cshtml
@model Uber.SDK.Models.PriceEstimateCollection
@{
    ViewBag.Title = "Price estimates";
}
<h2>@ViewBag.Title</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Estimate</th>
    </tr>
@foreach (var p in Model.PriceEstimates)
{
    <tr>
        <td>@p.ProductId</td>
        <td>@p.DisplayName</td>
        <td>@p.Estimate</td>
    </tr>
}
</table>

examples/Uber.Website/Views/Product/Index.cshtml
@model dynamic
@{
    ViewBag.Title = "Products";
}
<h2>@ViewBag.Title</h2>
@using (Html.BeginForm())
{
    <div>
        <label for="startlat">Start latitude</label>
        <input type="text" name="startlat" value="-37.8602828" />
    </div>
    <div>
        <label for="startlng">Start longitude</label>
        <input type="text" name="startlng" value="145.079616" />
    </div>
    <div>
        <input type="submit" value="Go" />
    </div>
}

examples/Uber.Website/Views/Product/Results.cshtml
@model Uber.SDK.Models.ProductCollection
@{
    ViewBag.Title = "Products";
}
<h2>@ViewBag.Title</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Image</th>
    </tr>
@foreach (var t in Model.Products)
{
    <tr>
        <td>@t.ProductId</td>
        <td>@t.DisplayName</td>
        <td>@t.Description</td>
        <td><img src="@t.Image" /></td>
    </tr>
}
</table>

examples/Uber.Website/Views/Request/Cancel.cshtml
@model bool
@{
    ViewBag.Title = "Request cancelled";
}
<h2>@ViewBag.Title</h2>
@if (Model)
{
    <p>Request has been cancelled.</p>
}
else
{
    <p>Request has not been cancelled.</p>
}

examples/Uber.Website/Views/Request/Create.cshtml
@{
    ViewBag.Title = "Make request";
}
<h2>@ViewBag.Title</h2>
@using (Html.BeginForm())
{
    <div>
        <label for="startlat">Start latitude</label>
        <input type="text" name="productId" value="@ViewBag.ProductId" />
    </div>
    <div>
        <label for="startlat">Start latitude</label>
        <input type="text" name="startlat" value="-37.8602828" />
    </div>
    <div>
        <label for="startlng">Start longitude</label>
        <input type="text" name="startlng" value="145.079616" />
    </div>
    <div>
        <label for="endlat">End latitude</label>
        <input type="text" name="endlat" value="-38.3436789" />
    </div>
    <div>
        <label for="endlng">End longitude</label>
        <input type="text" name="endlng" value="144.7430275" />
    </div>
    <div>
        <input type="submit" value="Go" />
    </div>
}

examples/Uber.Website/Views/Request/Index.cshtml
@using Uber.Website.Helpers
@model Uber.SDK.Models.UserActivity
@{
    ViewBag.Title = "User activity";
}
<h2>@ViewBag.Title</h2>
@if (Model == null)
{
    <p>Couldn't get user activity...</p>
}
else
{
    if (Model.History.Any())
    {
        foreach (var h in Model.History)
        {
            <p><span class="wd">Requested</span>@DateTimeHelper.UnixToDateTime(h.RequestTime)</p>  
            <p><span class="wd">Status</span>@h.Status</p>
            <p><span class="wd">Start time</span>@DateTimeHelper.UnixToDateTime(h.StartTime)</p>
            <p><span class="wd">End time</span>@DateTimeHelper.UnixToDateTime(h.EndTime)</p>
            <p><span class="wd">Distance</span>@h.Distance</p>
            <p>@Html.ActionLink("View request", "Show", "Request", new { requestId = h.Id }, null)</p>
            <p>@Html.ActionLink("View map", "Map", "Request", new { requestId = h.Id }, null)</p>
        }
    }
    else
    {
        <p>User has no history...</p>
    }
}

examples/Uber.Website/Views/Request/Map.cshtml
@model Uber.SDK.Models.RequestMap
@{
    ViewBag.Title = "Request map";
}
<h2>@ViewBag.Title</h2>
@if (Model == null)
{
    <p>Couldn't get map...</p>
}
else
{
    <p><span class="wd">ID</span>@Model.RequestId</p>
    <p><img src="@Model.Href"/></p>
}

examples/Uber.Website/Views/Request/Show.cshtml
@model Uber.SDK.Models.RequestDetails
@{
    ViewBag.Title = "Request details";
}
<h2>@ViewBag.Title</h2>
@if (Model == null)
{
    <p>Couldn't get user activity...</p>
}
else
{
    <p><span class="wd">ID</span>@Model.RequestId</p>
    <p><span class="wd">Status</span>@Model.Status</p>
    <p><span class="wd">ETA</span>@(Model.ETA == null ? "NA" : Model.ETA.ToString())</p>
    if (Model.Driver != null)
    {
        <p><span class="wd">Driver</span>@Model.Driver.Name</p>
        <p><img src="@Model.Driver.PictureUrl" /></p>
    }
    else
    {
        <p><span class="wd">Driver</span>NA</p>
    }
    if (Model.Vehicle != null)
    {
        <p><span class="wd">Vehicle</span>@Model.Vehicle.Make @Model.Vehicle.Model</p>
        <p><img src="@Model.Vehicle.PictureUrl" /></p>
    }
    else
    {
        <p><span class="wd">Vehicle</span>NA</p>
    }
    if (Model.Location != null)
    {
        <p><span class="wd">Latitude</span>@Model.Location.Latitude</p>
        <p><span class="wd">Longitude</span>@Model.Location.Longitude</p>
    }
    else
    {
        <p><span class="wd">Location</span>NA</p>
    }
    <p>@Html.ActionLink("Cancel", "Cancel", "Request", new { requestId = Model.RequestId }, null)</p>
    <p>@Html.ActionLink("Change to processing", "UpdateStatus", "Request", new { requestId = Model.RequestId, status = "processing" }, null)</p>
    <p>@Html.ActionLink("Change to accepted", "UpdateStatus", "Request", new { requestId = Model.RequestId, status = "accepted" }, null)</p>
    <p>@Html.ActionLink("Change to arriving", "UpdateStatus", "Request", new { requestId = Model.RequestId, status = "arriving" }, null)</p>
    <p>@Html.ActionLink("Change to in progress", "UpdateStatus", "Request", new { requestId = Model.RequestId, status = "in_progress" }, null)</p>
    <p>@Html.ActionLink("Change to driver cancelled", "UpdateStatus", "Request", new { requestId = Model.RequestId, status = "driver_canceled" }, null)</p>
    <p>@Html.ActionLink("Change to completed", "UpdateStatus", "Request", new { requestId = Model.RequestId, status = "completed" }, null)</p>
}

examples/Uber.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Uber API - @ViewBag.Title</title>
    <link rel="stylesheet" href="/assets/style.css" />
</head>
    <body>
        <h1>Uber API</h1>
        <a href="/">Home</a>
        @RenderBody()
        <script src="/assets/script.js"></script>
    </body>
</html>

examples/Uber.Website/Views/TimeEstimate/Index.cshtml
@model dynamic
@{
    ViewBag.Title = "Time estimate";
}
<h2>@ViewBag.Title</h2>
@using (Html.BeginForm())
{
    <div>
        <label for="startlat">Start latitude</label>
        <input type="text" name="startlat" value="-37.8602828" />
    </div>
    <div>
        <label for="startlng">Start longitude</label>
        <input type="text" name="startlng" value="145.079616" />
    </div>
    <div>
        <input type="submit" value="Go" />
    </div>
}

examples/Uber.Website/Views/TimeEstimate/Results.cshtml
@model Uber.SDK.Models.TimeEstimateCollection
@{
    ViewBag.Title = "Time estimates";
}
<h2>@ViewBag.Title</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Estimate</th>
    </tr>
@foreach (var t in Model.TimeEstimates)
{
    <tr>
        <td>@t.ProductId</td>
        <td>@t.DisplayName</td>
        <td>@t.Estimate</td>
    </tr>
}
</table>

examples/Uber.Website/Views/User/Index.cshtml
@model Uber.SDK.Models.UserProfile
@{
    ViewBag.Title = "User";
}
<h2>@ViewBag.Title</h2>
@if (Model == null)
{
    <p>Couldn't get user profile...</p>
}
else
{
    <p>Found user profile:</p>
    <p><img src="@Model.Picture" /></p>
    <p><span class="wd">ID</span>@Model.Id</p>
    <p><span class="wd">Email</span>@Model.Email</p>
    <p><span class="wd">Name</span>@Model.FirstName @Model.LastName</p>
}